### ISSUE TITLE
How to configure cloud ubuntu GPU with windows?

### ISSUE THREAD

**Issue by patsanchique** [alievk/avatarify#176]
Hello, i have cloud  ubuntu 18.04.4 2080ti
How can i configure this to work with my windows os?

**Comment by alievk** [comment]
Hi,

Just follow the wiki page to install the server in the cloud.

You will also need to install Avatarify on your Windows machine (don't download model weights). Then use this command to connect to the server:
```
run_windows.bat --worker-host address
```
where `address` is the address your server.

**Comment by E3V3A** [comment]
It's quite messy. Dealing with Firewall issues in Windows just sucks, and you will have to unless you wanna turn them off on both ends and leave your PC wide open for instant hack from the internet...

> Just follow the wiki page

Is not at all straight forward for a non-cloud expert and may not even work when in regions outside the US. I've now tried AWS, Google, nginx and Hamachi solutions, and they all suck for any non-expert. I got the *Hamachi* solution to "work", and the lag was enormous. ending at a FPS of 0.1. (I.e. 10 second per frame!)  Windows FW config was a royal PITA. We need better docs on this. I'll see if I can add my input somewhere, but since I don't have edit access to Wiki, it will probably take a while...

**Comment by alievk** [comment]
You can write in Wiki in your fork.

**Comment by E3V3A** [comment]
> You can write in Wiki in your fork.

That's exactly why it will take a while. I don't want to waste my time making write-ups in a place that will not be seen or found by anyone. ;)

**Comment by alievk** [comment]
There's also an option to open an issue and label it as `documentation`, I will then move it to the Wiki when it's ready.

**Comment by JohanAR** [comment]
Closing issue since we never heard from its creator again
