### ISSUE TITLE
Ubuntu/Google Colab  -     ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by GutlapalliNikhil** [alievk/avatarify#206]
I am trying with Google Colab and Ubuntu. At last when I was starting client, I was getting error as No module named 'yaml' in File "afy/cam_fomm.py.
![error](https://user-images.githubusercontent.com/33520288/83965246-e90f1d80-a8cf-11ea-9233-30739ebe6e0d.png)

**Comment by jeffrywu28** [comment]
in my linux me too

**Comment by alievk** [comment]
Do you see any errors during installation?
This should not normally happen since pyyaml is in the [requirements](https://github.com/alievk/avatarify/blob/master/requirements.txt#L19) and should be installed when you run [install.sh](https://github.com/alievk/avatarify/blob/master/scripts/install.sh#L31)

**Comment by jeffrywu28** [comment]
solved sir... using this command :
pip install pyyaml
pip install requests
pip install cv2
pip install scipy
pip install face_alignment
pip install sklearn
pip install pandas

**Comment by GutlapalliNikhil** [comment]
Thankyou @alievk and @jeffrywu28. I used all the commands and it worked.
