### ISSUE TITLE
vox-adv-cpk.pth.tar file is broken or not supported

### ISSUE THREAD

**Issue by Lohith0510** [alievk/avatarify#223]
**Broken TAR file format**

**To Upload a new file whic is clean**

**Info (please complete the following information):**
 - OS: Windows 
 - GPU model: Nvidia GeForce GTX 1050

 - Any other relevant information: 
The file in video tutorial is 512MB but the file in the link you've
 provided has got only 228MB. This is considered as a damaged file has been given. Kindly, I request you to re ploasd the file to a proper one

**Screenshots**

**Logs**

**Comment by alievk** [comment]
What do you mean by broken? Did you try running the app with this file?

The file is 229MB now as we pruned auxiliary data from it, but it still should work.

**Comment by Lohith0510** [comment]
I didnt work sir
I followed the instructions which are mentioned in the video tutorial

**Comment by Lohith0510** [comment]
This is what I get.....Kindly check and resolve my issue, sir

**Comment by alievk** [comment]
Could you show the output of the terminal?

**Comment by Lohith0510** [comment]
Kindly waiting for your reply, sir
Regards

**Comment by WitherstormG** [comment]
I'm having the same issue, It states "FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar' " any ideas?

**Comment by JohanAR** [comment]
> I'm having the same issue, It states "FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar' " any ideas?

That is not the same issue, OP was claiming that the tar file is broken. Your problem is that you haven't downloaded the file vox-adv-cpk.pth.tar to the correct directory. Check the install instructions and verify that you have followed every step, especially step 3 if you have Linux or step 5 if you have Windows, since those are related to downloading that file. Maybe you put it in the wrong directory.

Closing this issue because OP failed to provide the requested information, but if you @WitherstormG need further assistance you can open a new issue.

**Comment by bennyreigns** [comment]
vox-adv-cpk.pth.tar says cannot open file as archive error i need solutions pls
