### ISSUE TITLE
PlaidML+OpenCL to increase Mac OS performance

### ISSUE THREAD

**Issue by appspell** [alievk/avatarify#23]
Can we use PlaidML+OpenCL bundle instead of CUDA for torch to increase performance for Mac OS?

**Comment by diogopublio** [comment]
that sounds like a good idea

**Comment by alievk** [comment]
Sound like a tons of work :)

Pytorch is not going to support OpenCL [officially](https://github.com/pytorch/pytorch/issues/488#issuecomment-273626736).

In my opinion it's more effective and easier to target the neural network to specific hardware rather than adding/waiting for OpenCL support for a deep learning framework.

**Comment by suvl** [comment]
Came here to ask for OpenCL support. Well, fair enough, gonna scrap a USB-C external card somewhere. Any suggestions?
