### ISSUE TITLE
Error while executing run_windows.bat File (In line 38 Python file cam_fomm)

### ISSUE THREAD

**Issue by m4xx101** [alievk/avatarify#87]
```
C:\Users\m4xx\Downloads\avatarify-master>run_windows.bat

C:\Users\m4xx\Downloads\avatarify-master>REM Web-camera device id

C:\Users\m4xx\Downloads\avatarify-master>set CAMID=0

C:\Users\m4xx\Downloads\avatarify-master>REM ################################################

C:\Users\m4xx\Downloads\avatarify-master>REM Normally you don't want to change settings below

C:\Users\m4xx\Downloads\avatarify-master>REM Conda environment name

C:\Users\m4xx\Downloads\avatarify-master>set CONDA_ENV_NAME=avatarify
'conda' is not recognized as an internal or external command,
operable program or batch file.
  File "cam_fomm.py", line 38
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],**config['model_params']['common_params'])
                                                                                    ^
SyntaxError: invalid syntax
```

**Comment by phreaker0** [comment]
`'conda' is not recognized as an internal or external command,
operable program or batch file.`
It seems you didn't install miniconda correctly: https://github.com/alievk/avatarify#windows

**Comment by devTenshi** [comment]
'python' is not recognized as an internal or external command,
operable program or batch file.


this is what I get every time I do > run_windows.bat
any solution?

**Comment by adindu11** [comment]
Hello Please I Get The Bellow Message Each Time I Try To Do } run_windows.bat. 
Please What Do i Need To Do Because after downloading and place vox-adv-cpk.pth.tar file in the avatarify-python directory and then run_windows.bat i get the messages bellow please what do i do next. thanks

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
(base) PS C:\Users\pc\avatarify-python>
