### ISSUE TITLE
Why are my avatars eyes are always shut...

### ISSUE THREAD

**Issue by E3V3A** [alievk/avatarify#99]
I'm trying to understand why my avatar has the eyes shut. The only exception is when I look at the camera but not directly facing it at an angle of about 45 degrees. Any idea what's going on?

**Comment by alievk** [comment]
When you hit X button, it saves your face position and expression for the later calculations of face movements. Say, if the avatars eyes are looking straight in the camera and you are looking away (at the moment you pressed X), then when you look in the camera the avatar will look away.

The same happens if avatar's head is slightly turned. If you want the avatar's head turn to the camera when you turn to the camera then you have to match the avatars head position at the moment of calibration.

**Comment by E3V3A** [comment]
@alievk  Great! Thank you! 
BTW. I would like to edit and make an FAQ on your Wiki, can you give me permission to do so?
Cheers!
